-- MySQL Script generated by MySQL Workbench
-- Tue May 19 12:15:19 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sistema_mensajes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistema_mensajes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistema_mensajes` DEFAULT CHARACTER SET utf8 ;
USE `sistema_mensajes` ;

-- -----------------------------------------------------
-- Table `sistema_mensajes`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_mensajes`.`roles` (
  `id_rol` INT NOT NULL AUTO_INCREMENT,
  `nombre_rol` VARCHAR(50) NOT NULL,
  `descripcion_rol` VARCHAR(300) NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT NULL,
  `deleted` TINYINT(1) DEFAULT 0,
  -- Borrado logico - no se borra el registro fisicamente
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB;

-- DIEGO MUERE- DEBEMOS SACARLO DEL SISTEMA. BORRADO FISICO DELETE FROM USUARIO
-- CON DELETE EL DATO DEJA DE EXISTIR - NO SE PUEDE RECUPERAR
-- EN CAMBIO CON BORRADO LOGICO (campo deleted activo - deleted 1))
-- PODEMOS OCULTAR EL USUARIO PARA QUE EL CLIENTE NO LO VEA
-- PERO NO SALE DEL SISTEMA.

-- -----------------------------------------------------
-- Table `sistema_mensajes`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_mensajes`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT NULL,
  `deleted` TINYINT(1) DEFAULT 0,
  `id_rol` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_usuarios_roles1_idx` (`id_rol` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_roles1`
  FOREIGN KEY (`id_rol`)
  REFERENCES `sistema_mensajes`.`roles` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_mensajes`.`mensajes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_mensajes`.`mensajes` (
  `id_mensaje` INT NOT NULL AUTO_INCREMENT,
  `contenido` TEXT NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT NULL,
  `deleted` TINYINT(1) DEFAULT 0,
  `emisor` INT NOT NULL,
  `receptor` INT NOT NULL,
  PRIMARY KEY (`id_mensaje`),
  INDEX `fk_mensajes_usuarios_idx` (`emisor` ASC) VISIBLE,
  INDEX `fk_mensajes_usuarios1_idx` (`receptor` ASC) VISIBLE,
  CONSTRAINT `fk_mensajes_usuarios`
    FOREIGN KEY (`emisor`)
    REFERENCES `sistema_mensajes`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mensajes_usuarios1`
    FOREIGN KEY (`receptor`)
    REFERENCES `sistema_mensajes`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_mensajes`.`comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_mensajes`.`comentarios` (
  `id_comentario` INT NOT NULL AUTO_INCREMENT,
  `contenido` TEXT NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT NULL,
  `deleted` TINYINT(1) DEFAULT 0,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_comentario`),
  INDEX `fk_comentarios_usuarios1_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_comentarios_usuarios1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `sistema_mensajes`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- Insertar datos en tablas
USE sistema_mensajes;
INSERT INTO roles(nombre_rol, descripcion_rol) 
VALUES ("admin", "control total"),
("usuario comun", "permisos administrativos basicos"),
("invitado", "usuario temporal con permisos limitados");
INSERT INTO usuarios(nombre, password_hash, email, id_rol) 
VALUES ("randy123", "randy123", "randy@gmail.com", 2),
("akon123", "akon123", "akon@gmail.com", 1),
("tete", "tete", "tete@gmail.com", 2),
("anne", "anne", "anne@gmail.com", 3),
("martin", "martin", "martin@gmail.com", 3);
SELECT * from roles;
SELECT * from usuarios;
INSERT INTO comentarios (contenido, created_by, id_usuario) 
VALUES("hola este es un comentario", 1, 1),
("hola soy el akon admin", 2, 2),
("hola soy la tete", 3, 3);
SELECT * from comentarios;

INSERT INTO mensajes(contenido, created_by, id_usuario)
VALUES ("hola martin, eres el mejor", 1, 1, 5),
("hola tete, ¿hiciste la tarea?", 4, 4, 3),
("hola randy, mañana es feriado", 3, 3, 1);

SELECT * from mensajes;
-- CONSULTAS SIMPLES CON CONDICION
-- WHERE EN MYSQL
-- MOSTRAR MENSAJES DONDE EL REMITENTE SEA RANDY
SELECT contenido, emisor
from mensajes
WHERE emisor = 1; -- WHERE aplica condicion sobre consulta

-- MOSTRAR USUARIOS QUE ESTAN ACTIVOS (DELETED 0)
SELECT nombre, email, id_rol, deleted
from usuarios
WHERE deleted = 0;

-- MOSTRAR USUARIOS QUE ESTAN ELIMINADOS (DELETED 1)
SELECT nombre, email, id_rol, deleted
from usuarios
WHERE deleted = 1;

-- BORRAR UN USUARIO
UPDATE usuarios
SET deleted = 1
WHERE id_usuario = 2;

-- RECUPERAR UN USUARIO
UPDATE usuarios
SET deleted = 0
WHERE id_usuario = 1;
-- TAREA
-- MOSTRAR ROLES DE USUARIO
SELECT nombre_rol, descripcion_rol
from roles
WHERE deleted = 0;

-- ELIMINAR 2 ROLES
UPDATE roles
SET  deleted = 1
WHERE id_rol IN (2, 3);

-- RECUPERAR 1 ROL DE USUARIO
UPDATE roles
SET deleted = 0
WHERE id_rol = 2;

SELECT nombre_rol, descripcion_rol
from roles
WHERE deleted = 0;