-- MySQL Script generated by MySQL Workbench
-- Tue May 19 12:15:19 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`roles` (
    `id_rol` INT NOT NULL AUTO_INCREMENT,
    `nombre_rol` VARCHAR(50) NOT NULL,
    `descripcion_rol` VARCHAR(300) NOT NULL,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `created_by` INT NULL,
    `deleted` TINYINT(1) DEFAULT 0,
    -- Borrado logico - no se borra el registro
    PRIMARY KEY (`id_rol`))
ENGINE = InnoDB;

-- DIEGO MUERE- DEBEMOS SACARLO DEL SISTEMA. BORRADO FISICO DELETE FROM USUARIO
-- CON DELETE EL DATO DEJA DE EXISTIR - NO SE PUEDE RECUPERAR
-- EN CAMBIO CON BORRADO LOGICO (campo deleted activo - deleted 1))
-- PODEMOS OCULTAR EL USUARIO PARA QUE EL CLIENTE NO LO VEA
-- PERO NO SALE DEL SISTEMA.

-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
    `id_usuario` INT NOT NULL AUTO_INCREMENT,
    `nombre` VARCHAR(100) NOT NULL,
    `email` VARCHAR(150) NOT NULL,
    `password_hash` VARCHAR(255) NOT NULL,
    `created_at` DATETIME NULL,
    `updated_at` DATETIME NULL,
    `created_by` INT NULL,
    `deleted` TINYINT(1) NULL,
    `id_rol` INT NOT NULL,
    PRIMARY KEY (`id_usuario`),
    UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE,
    UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_usuarios_roles1_idx` (`id_rol` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_roles1`
    FOREIGN KEY (`id_rol`)
    REFERENCES `mydb`.`roles` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`mensajes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`mensajes` (
  `id_mensaje` INT NOT NULL AUTO_INCREMENT,
  `contenido` TEXT NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `created_by` INT NULL,
  `deleted` TINYINT(1) NULL,
  `emisor` INT NOT NULL,
  `receptor` INT NOT NULL,
  PRIMARY KEY (`id_mensaje`),
  INDEX `fk_mensajes_usuarios_idx` (`emisor` ASC) VISIBLE,
  INDEX `fk_mensajes_usuarios1_idx` (`receptor` ASC) VISIBLE,
  CONSTRAINT `fk_mensajes_usuarios`
    FOREIGN KEY (`emisor`)
    REFERENCES `mydb`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mensajes_usuarios1`
    FOREIGN KEY (`receptor`)
    REFERENCES `mydb`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comentarios` (
  `id_comentario` INT NOT NULL AUTO_INCREMENT,
  `contenido` TEXT NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `created_by` INT NULL,
  `deleted` TINYINT(1) NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_comentario`),
  INDEX `fk_comentarios_usuarios1_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_comentarios_usuarios1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;